apiVersion: apps/v1
kind: Deployment
metadata:
  name: lede-test1
spec:
  selector:
    matchLabels:
      app: lede-test
  replicas: 20
  template:
    metadata:
      labels:
        app: lede-test
    spec:
      containers:
      - name: lede
        image: httpd
        command:
        imagePullPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: concentration
                operator: Lt
                values:
                - "80"

