apiVersion: apps/v1
kind: Deployment
metadata:
  name: lede-test1
spec:
  selector:
    matchLabels:
      app: lede-test
  replicas: 70
  template:
    metadata:
      labels:
        app: lede-test
    spec:
      containers:
      - name: lede
        image:  lede-17.01.5:latest
        command: ["/bin/ash", "-ce", "tail -f /dev/null"]
        imagePullPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: concentration
                operator: Gt
                values:
                - "80"

